### ISSUE TITLE
Help proposal and question

### ISSUE THREAD

**Issue by climu** [domeav/ASRbot#1]
Hi,
I know quite a bit about [asr league php app](https://github.com/PatrickJAMET/ASR), so if you have any questions, feels free to ask.

Also, I am wondering how you gather league players list.

A php page that ask class from req and return a json, txt file with the list of player would be easy to do...

Good work here !

**Comment by domeav** [comment]
Hello!
The player list is parsed from the ASR website results page, but I could switch to any source that would be more standard: let me know if you or someone would do it (json would be perfect). But it works fine as it is as long as the markup doesn't change too much.

**Comment by climu** [comment]
ok,
I will talk to asr admins to see if I can do it.
In the meantime, did you noticed this page:
 http://www.advancedstudyroom.org/asrleague/league-iframe.php?room=alpha

You can remove the req request but anyway it is cleaner than http://www.advancedstudyroom.org/results/
