### ISSUE TITLE
Adapt for OSR

### ISSUE THREAD

**Issue by climu** [domeav/ASRbot#3]
Hi,
I just created a new study/league room on kgs and I was wondering if you would be interested in adapting your bot for it.
You can check our website [here](openstudyroom.org) and check out our code [here](https://github.com/climu/openstudyroom). Let me know if you are interested.

**Comment by domeav** [comment]
Hello climu,
I'm glad you started OSR, and I wish you success! I might join one of these days. It should be pretty trivial to adapt the code to OSR (as long as you're playing on KGS) but I'd rather let someone of your new team take over. I'll be glad to answer any question!
